#server:
#  error:
#    include-stacktrace: on_param
#    include-message: on_param

spring:
  datasource:
    url: jdbc:h2:mem:app-db
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: h2

logging:
  level:
    root: INFO
    web: DEBUG

jwt-secret: 904c3afdffa4742c4d948656b688d45c830ff3d089686777607e5fa4956a6994
