spring:
  application:
    name: taskManager
  jpa:
    properties:
      hibernate:
        format_sql: true
#        hbm2ddl:
#          create_namespaces: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger.html

base-url: /api
