spring:
  application:
    name: taskManager
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    default: dev

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger.html

base-url: /api
